name: k6 Performance

on:
  workflow_dispatch:
    inputs:
      base_url:
        description: "Base URL"
        required: true
      profile:
        description: "Profile"
        required: true
        default: "load"
        type: choice
        options:
          - load
          - stress
          - spike
          - endurance

jobs:
  k6:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Make run.sh executable
        run: chmod +x run.sh

      - name: Run K6
        run: ./run.sh "${{ github.event.inputs.base_url }}" "${{ github.event.inputs.profile }}"

      - name: Upload K6 Reports
        uses: actions/upload-artifact@v4
        with:
          name: k6-report
          path: reports/
