name: k6 Performance

on:
  workflow_dispatch:
    inputs:
      base_url:
        description: "Base URL"
        required: true
      profile:
        description: "Profile"
        required: true
        default: "load"
        type: choice
        options:
          - load
          - stress
          - spike
          - endurance

jobs:
  k6:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create reports dir
        run: mkdir -p reports

      - name: Run k6
        uses: grafana/k6-action@v0.3.1
        with:
          filename: tests/performance.js
          flags: >
            --summary-export=reports/summary.json
        env:
          BASE_URL: ${{ github.event.inputs.base_url }}
          PROFILE: ${{ github.event.inputs.profile }}
          K6_WEB_DASHBOARD: "true"
          K6_WEB_DASHBOARD_EXPORT: "reports/index.html"

      - name: Debug reports
        run: ls -la reports

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: k6-report
          path: reports/
